my_portfolio/base/urls.py
from django.urls import path
from base.views import home, fetch_posts, create_post, update_post, view_post, delete_post, view_profile, send_email

urlpatterns = [
    path('', home, name='home'),
    path('posts/', fetch_posts, name='posts'),
    path('post/<slug:slug>/', view_post, name='post'),
    path('profile/', view_profile, name='profile'),

    # CRUD PATHS

    path('create_post/', create_post, name='create_post'),
    path('update_post/<slug:slug>/', update_post, name='update_post'),
    path('delete_post/<slug:slug>/', delete_post, name='delete_post'),


    path('send_email/', send_email, name='send_email'),
]

my_portfolio/my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_portfolio/base/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(
        null=True, blank=True, upload_to="images", default="project-mockup-example.jpeg")
    body = models.TextField(null=True, blank=True)
    live_url=models.URLField(max_length = 200, null=True, blank=True)
    code_url=models.URLField(max_length = 200, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    features = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True)
    slug= models.SlugField(null=True, blank=True)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):

        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug

        super().save(*args, **kwargs)

my_portfolio/base/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = '__all__'

        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

my_portfolio/base/views/create_post.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from base.forms import PostForm


@login_required(login_url='home')
def create_post(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')
    context = {'form': form}
    return render(request, 'base/post_form.html', context)

my_portfolio/base/views/delete_post.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from base.models import Post


@login_required(login_url='home')
def delete_post(request, slug):
    post = Post.objects.get(slug=slug)

    if request.method == 'POST':
        post.delete()
        return redirect('posts')
    context = {'item': post}
    return render(request, 'base/delete.html', context)

my_portfolio/base/views/fetch_posts.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from base.filters import PostFilter
from base.models import Post


def fetch_posts(request):

    posts = Post.objects.filter(active=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs

    page = request.GET.get('page')
    paginator = Paginator(posts, 3)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'myFilter': myFilter}
    return render(request, 'base/posts.html', context)

my_portfolio/base/views/home.py
from django.shortcuts import render
from base.models import Post


def home(request):

    posts = Post.objects.filter(active=True, features=True)[0:3]
    context = {'posts': posts}
    return render(request, 'base/index.html', context)

my_portfolio/base/views/send_email.py
from django.shortcuts import render
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string


def send_email(request):

    if request.method == 'POST':
        template = render_to_string('base/email_template.html', {
            'name': request.POST['name'],
            'email': request.POST['email'],
            'message': request.POST['message'],
        })

        email = EmailMessage(request.POST['subject'], template, settings.EMAIL_HOST_USER, [
                             'pkgupta5071453@gmail.com'])
        email.fail_silently = False
        email.send()
    return render(request, 'base/email_send.html')

my_portfolio/base/views/update_post.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from base.forms import PostForm
from base.models import Post


@login_required(login_url='home')
def update_post(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')
    context = {'form': form}
    return render(request, 'base/post_form.html', context)

my_portfolio/base/views/view_post.py
from django.shortcuts import render

from base.models import Post


def view_post(request, slug):
    post = Post.objects.get(slug=slug)
    context = {'post': post}
    return render(request, 'base/project.html', context)

my_portfolio/base/views/view_profile.py
from django.shortcuts import render


def view_profile(request):
    return render(request, 'base/profile.html')

my_portfolio/base/templates/base/delete.html
{%extends 'base/main.html' %}
{%load static%}
{%block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<div class="main-container">
    <form method='POST' action="">
        {%csrf_token %}
        <h1>Are you sure you want to delete {{item}}?</h1>
        <input class="btn btn-danger" type="submit" value="Confirm" />
    </form>
</div>
<br>
<br>
<br>
<br>
<br>
{%endblock content %}

my_portfolio/base/templates/base/email_send.html
{%extends 'base/main.html'%}
{%load static %}

{% block content %}

<style type="text/css">
    html, body {
        height: 100%;
    }
    #page-wrapper {
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #eaeaea;
    }

    h1 {
        font-size: 40px;
    }

    a,p{
        font-size:20px;
    }

    #success-box {
        max-width: 800px;
        height: auto;
        background-color: #fff;
        border: 1px solid #888;
        border-radius: 5px;
        paddings: 15px;

    }
    #success-box p{
        font-size: 18px;
    }
</style>


<div id='page-wrapper'>
    <div id='success-box' class='content-block'>
        <h1>Thanks for reaching out!</h1>
        <p>Your message was successfully sent. I will do my best to get back to you in timely manner :)</p>
        <a id='back-btn' class='btn btn-success' href="{% url 'home' %}">BACK TO PAGE</a>
    </div>
</div>



{% endblock content %}

my_portfolio/base/templates/base/email_template.html
{{message}}
{{email}}
{{name}}

my_portfolio/base/templates/base/index.html
{%extends 'base/main.html'%}
{%load static %}

{% block content %}
<section class="home-hero">
  <div class="home-hero__content">
    <h1 class="heading-primary">Hey, I'm Pawan Gupta</h1>
    <div class="home-hero__info">
      <p class="text-primary">
        A Backend focused Full Stack Python Web Developer building the Backend of Websites and Web Applications that
        leads to the success of the overall product
      </p>
    </div>
    <div class="home-hero__cta">
      <a href="./#projects" class="btn btn--bg">Projects</a>
    </div>
  </div>
  <div class="home-hero__socials">
    <div class="home-hero__social">
      <a href="https://www.linkedin.com/in/pawan-gupta03/" class="home-hero__social-icon-link">
        <img src="{%static 'images/linkedin-ico.png'%}" alt="icon" class="home-hero__social-icon" />
      </a>
    </div>
    <div class="home-hero__social">
      <a href="https://github.com/pawangupta5071" class="home-hero__social-icon-link">
        <img src="{%static 'images/github-ico.png'%}" alt="icon" class="home-hero__social-icon" />
      </a>
    </div>
    <div class="home-hero__social">
      <a href="https://twitter.com/pawan_____gupta" class="home-hero__social-icon-link">
        <img src="{%static 'images/twitter-ico.png'%}" alt="icon" class="home-hero__social-icon" />
      </a>
    </div>
    <div class="home-hero__social">
      <a href="https://www.instagram.com/pawan_____gupta/" class="home-hero__social-icon-link home-hero__social-icon-link--bd-none">
        <img src="{%static 'images/insta-ico.png'%}" alt="icon" class="home-hero__social-icon" />
      </a>
    </div>
  </div>
  <div class="home-hero__mouse-scroll-cont">
    <div class="mouse"></div>
  </div>
</section>
<section id="about" class="about sec-pad">
  <div class="main-container">
    <h2 class="heading heading-sec heading-sec__mb-med">
      <span class="heading-sec__main">About Me</span>
      <span class="heading-sec__sub">
        Here you will find more information about me, what I do, and my current skills mostly in terms of programming
        and technology
      </span>
    </h2>
    <div class="about__content">
      <div class="about__content-main">
        <h3 class="about__content-title">Get to know me!</h3>
        <div class="about__content-details">
          <p class="about__content-details-para">
            I'm a
            <strong>Python Developer</strong>
            building the Front-end of Websites and Web Applications that leads to the success of the overall product.
            Check out some of my work in the
            <strong>Project</strong> section.

          </p>
          <p class="about__content-details-para">
            I also like sharing content related to the stuff that I have learned over the years in <strong>Web
              Development</strong> so it can help other people of the Dev Community. Feel free to Connect or Follow me
            on my <a rel="noreferrer" href="https://www.linkedin.com/in/pawan-gupta03/" target="_blank">Linkedin</a>  where I post useful content related to Web Development and Programming.

          </p>
          </p>
          <p class="about__content-details-para">
            I'm open to <strong>job</strong> opportunities where I can contribute, learn and grow. If you have a good
            opportunity that matches my skills and experience then don't hesitate to
            <strong>contact</strong> me.
          </p>
        </div>
        <a href="./#contact" class="btn btn--med btn--theme dynamicBgClr">Contact</a>
      </div>
      <div class="about__content-skills">
        <h3 class="about__content-title">My Skills</h3>
        <div class="skills">
          <div class="skills__skill">PYTHON</div>
          <div class="skills__skill">DJANGO</div>
          <div class="skills__skill">JavaScript</div>
          <div class="skills__skill">BootStrap</div>
          <div class="skills__skill">DjangoRestFramework</div>
          <div class="skills__skill">GIT</div>
          <div class="skills__skill">Github</div>
          <div class="skills__skill">MySql</div>
          <div class="skills__skill">Html</div>
          <div class="skills__skill">Css</div>

        </div>
      </div>
    </div>
  </div>
</section>
<section id="projects" class="projects sec-pad">
  <div class="main-container">
    <h2 class="heading heading-sec heading-sec__mb-bg">
      <span class="heading-sec__main">Projects</span>
      <span class="heading-sec__sub">
        Here you will find some of the personal and clients projects that I created with each project containing its own
        case study
      </span>
    </h2>
    {%for post in posts%}
    <div class="projects__content">
      <div class="projects__row">
        <div class="projects__row-img-cont">
          <img src="{{post.thumbnail.url}}" alt="Software Screenshot" class="projects__row-img" loading="lazy" />
        </div>
        <div class="projects__row-content">
          <h3 class="projects__row-content-title">{{post.headline}}</h3>
          <p class="projects__row-content-desc">
            {{post.sub_headline}}
          </p>


          <a href="{% url "post" post.slug%}" class="btn btn--med btn--theme dynamicBgClr" target="_blank">Case Study</a>
          <br>
          <ul>
            {%for tag in post.tags.all %}
            <span style="display: inline-block;
                    color: #fff;
                    background-color: #888;
                    border-radius: 5px;
                    margin: 2px;
                    padding: 2px 5px;
                    font-size: 12px;">{{tag}}</span>
            {%endfor %}
            <ul>


        </div>
      </div>


    </div>

    {%empty%}
    <h3>NO post found...</h3>

    {%endfor %}
    <br>
    <button><a href="{% url "posts" %}" class="btn btn--med btn--theme-inv project-details__links-btn" target="_blank">MORE PROJECTS...</a></button>


        

  </div>
</section>
<section id="contact" class="contact sec-pad dynamicBg">
  <div class="main-container">
    <h2 class="heading heading-sec heading-sec__mb-med">
      <span class="heading-sec__main heading-sec__main--lt">Contact</span>
      <span class="heading-sec__sub heading-sec__sub--lt">
        Feel free to Contact me by submitting the form below and I will get back to you as soon as possible
      </span>
    </h2>
    <div class="contact__form-container">
      <form  class="contact__form" method="POST" action="{% url 'send_email' %}">
        {% csrf_token %}
        <div class="contact__form-field">
          <label class="contact__form-label" for="name">Name</label>
          <input required placeholder="Enter Your Name" type="text" class="contact__form-input" name="name" id="name" />
        </div>
        <div class="contact__form-field">
          <label class="contact__form-label" for="subject">subject</label>
          <input required placeholder="Enter Your subject" type="text" class="contact__form-input" name="subject" id="subject" />
        </div>
        <div class="contact__form-field">
          <label class="contact__form-label" for="email">Email</label>
          <input required placeholder="Enter Your Email" type="text" class="contact__form-input" name="email"
            id="email" />
        </div>
        <div class="contact__form-field">
          <label class="contact__form-label" for="message">Message</label>
          <textarea required cols="30" rows="10" class="contact__form-input" placeholder="Enter Your Message"
            name="message" id="message"></textarea>
        </div>
        <button type="submit" class="btn btn--theme contact__btn">
          Submit
        </button>
      </form>
    </div>
  </div>
</section>

{% endblock content %}

my_portfolio/base/templates/base/main.html
<!DOCTYPE html>
{%load static %}
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <link rel="icon" href="{%static 'images/favicon.ico'%}" type="image/x-icon" />
  <title>Pawan Gupta | Fullstack Python Developer</title>
  <meta name="description" content="A Backend focused Full Stack Python/Django Developer building the Backend of Websites and Web Applications that leads to the success of the overall product" />

  <meta name="author" content="Pawan Gupta" />

  <meta
      name="google-site-verification"
      content="wX2xdkxqjrC4rA2EM-9bbaVpiEEFG8ae5azgeZDd-oo"
    />

  <meta
    property="og:title"
    content="Pawan Gupta | Fullstack Python Developer"
  />


  
  <meta property="og:site_name" content="Pawan Gupta Portfolio Website" />
  <meta property="og:url" content="https://PawanGupta.onrender.com/" />
  <meta
    property="og:description"
    content="A Backend focused Full Stack Python/Django Developer building the Backend of Websites and Web Applications that leads to the success of the overall product"
  />
  <meta property="og:type" content="website" />
  
  

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700;900&display=swap"
    rel="stylesheet"
  />
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script
    async
    src="https://www.googletagmanager.com/gtag/js?id=G-QD9ESD1D9K"

    ></script>



  <link rel="stylesheet" href="{%static 'css/style.css'%}" />

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600;700;900&display=swap"
    rel="stylesheet" />
</head>

<body>
  <header class="header">
    <div class="header__content">
      <div onclick="window.location = '{% url 'home' %}';" class="header__logo-container">
        <div class="header__logo-img-cont">
          <img src="{%static 'images/pawan.jpeg'%}" alt="pawan gupta Logo Image" class="header__logo-img" />
        </div>
        <span class="header__logo-sub">Pawan Gupta</span>
      </div>
      <div class="header__main">
        <ul class="header__links">
          <li class="header__link-wrapper">
            <a href="{% url 'home' %}" class="header__link"> Home </a>
          </li>
          <li class="header__link-wrapper">
            <a href="{% url 'home' %}#about" class="header__link">About </a>
          </li>
          <li class="header__link-wrapper">
            <a href="{% url 'posts' %}" class="header__link">
              Projects
            </a>
          </li>
          <li class="header__link-wrapper">
            <a href="{% url 'home' %}#contact" class="header__link"> Contact </a>
          </li>
        </ul>
        <div class="header__main-ham-menu-cont">
          <img src="{%static 'svg/ham-menu.svg'%}" alt="hamburger menu" class="header__main-ham-menu" />
          <img src="{%static 'svg/ham-menu-close.svg'%}" alt="hamburger menu close"
            class="header__main-ham-menu-close d-none" />
        </div>
      </div>
    </div>
    <div class="header__sm-menu">
      <div class="header__sm-menu-content">
        <ul class="header__sm-menu-links">
          <li class="header__sm-menu-link">
            <a href="{% url 'home' %}"> Home </a>
          </li>

          <li class="header__sm-menu-link">
            <a href="{% url 'home' %}#about"> About </a>
          </li>

          <li class="header__sm-menu-link">
            <a href="{% url 'posts' %}"> Projects </a>
          </li>

          <li class="header__sm-menu-link">
            <a href="{% url 'home' %}#contact"> Contact </a>
          </li>
        </ul>
      </div>
    </div>
  </header>
  {% block content %}
  <!-- content goes here -->
  {% endblock %}


  <footer class="main-footer">
    <div class="main-container">
      <div class="main-footer__upper">
        <div class="main-footer__row main-footer__row-1">
          <h2 class="heading heading-sm main-footer__heading-sm">
            <span>Social</span>
          </h2>
          <div class="main-footer__social-cont">
            <a target="_blank" rel="noreferrer" href="https://www.linkedin.com/in/pawan-gupta03/">
              <img class="main-footer__icon" src="{%static 'images/linkedin-ico.png'%}" alt="icon" />
            </a>
            <a target="_blank" rel="noreferrer" href="https://github.com/pawangupta5071">
              <img class="main-footer__icon" src="{%static 'images/github-ico.png'%}" alt="icon" />
            </a>
            <a target="_blank" rel="noreferrer" href="https://twitter.com/pawan_____gupta">
              <img class="main-footer__icon" src="{%static 'images/twitter-ico.png'%}" alt="icon" />
            </a>
            
            <a target="_blank" rel="noreferrer" href="https://www.instagram.com/pawan_____gupta/">
              <img class="main-footer__icon main-footer__icon--mr-none" src="{%static 'images/insta-ico.png'%}"
                alt="icon" />
            </a>
          </div>
        </div>
        <div class="main-footer__row main-footer__row-2">
          <h4 class="heading heading-sm text-lt">Pawan Gupta</h4>
          <p class="main-footer__short-desc">
            A Backend focused Python Developer building the backend of Websites and Web Applications that leads to the
            success of the overall product.
          </p>
        </div>
      </div>

      <!-- If you give me some credit or shoutout here by linking to my website, then it will be a big thing for me and will help me a lot :) -->
      <div class="main-footer__lower">
        &copy; Copyright 2021. Made by
        <a rel="noreferrer" target="_blank" href="https://rammaheshwari.com">Ram Maheshwari</a>
      </div>
    </div>
  </footer>

  <script src="{%static 'js/index.js'%}">
    let index = "{% url 'home' %}"
  </script>
</body>

</html>

my_portfolio/base/templates/base/post_form.html
{% extends 'base/main.html'%}
{%load static%}
{%load crispy_forms_tags%}
{%block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<style type="text/css">
    #div_id_tags>div {
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;

    }
</style>
<div class="main-container">
    <h1>Post form</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{form|crispy}}
        <input class="btn btn-secondary" type="submit" value="Submit Post">
    </form>
</div>
<br>
{%endblock content %}

my_portfolio/base/templates/base/posts.html
{%extends 'base/main.html'%}
{%load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
  #id_tags {
    overflow-y: scroll;
    max-height: 100px;
    border: 1px solid #888;
    border-radius: 5px;
    padding: 5px;
  }


  ul li {
    display: inline-block;
  }

  .pagination a {
    font-size: 15px;
    border: 1px solid #ddd;
    margin: 0 4px;
    color: black;
    float: left;
    padding: 8px 16px;
    text-decoration: none;
  }

  .pagination a.active {
    background-color: #4CAF50;
    color: white;
    border-radius: 5px;
  }

  .pagination a:hover:not(.active) {
    background-color: #ddd;
    border-radius: 5px;
  }

  .row {
    text-align: center;
  }
</style>


<section id="projects" class="projects sec-pad">
  <div class="main-container">
    <h2 class="heading heading-sec heading-sec__mb-bg">
      <span class="heading-sec__main">Projects</span>

      <form id="serchForm" method="GET">Headline
        {{myFilter.form.headline}} <br>
        tags:
        {{myFilter.form.tags}}
        <input type="submit" value="search" class="btn btn-primary">
      </form>


      {%if request.user.is_authenticated%}
      <li><a href="{%url 'create_post'%}">Add Projects</a></li>
      {%endif%}
      <span class="heading-sec__sub">
        Here you will find some of the personal and clients projects that I created with each project containing its own
        case study
      </span>
    </h2>
    {%for post in posts%}
    <div class="projects__content">
      <div class="projects__row">
        <div class="projects__row-img-cont">
          <img src="{{post.thumbnail.url}}" alt="Software Screenshot" class="projects__row-img" loading="lazy" />
        </div>
        <div class="projects__row-content">
          <h3 class="projects__row-content-title">{{post.headline}}</h3>
          <p class="projects__row-content-desc">
            {{post.sub_headline}}
          </p>

          <a href="{% url 'post' post.slug %}" class="btn btn--med btn--theme dynamicBgClr" target="_blank">Case Study</a>

          {%if request.user.is_authenticated%}
          <li><a href="{%url 'update_post' post.slug%}" class="button primary edit" style="font-family:'Open Sans';
            font-size: 16px;
            font-weight:400;
            display:inline-block;
            color:#FFF;
            border-radius: .25em;
            text-shadow: -1px -1px 0px rgba(0,0,0,0.4);
            background:rgb(52, 152, 219);
            ">Edit</a>
            |<a href="{%url 'delete_post' post.slug%}" class="button primary delete" style="font-family:'Open Sans';
          font-size: 16px;
          font-weight:400;
          display:inline-block;
          color:#FFF;
          border-radius: .25em;
          text-shadow: -1px -1px 0px rgba(0,0,0,0.4);
          background:rgb(52, 152, 219);">Delete</a></li>
          {%endif%}

          <br>
          <ul>
            {%for tag in post.tags.all %}
            <span style="display: inline-block;
                  color: #fff;
                  background-color: #888;
                  border-radius: 5px;
                  margin: 2px;
                  padding: 2px 5px;
                  font-size: 12px;">{{tag}}</span>
            {%endfor %}
            <ul>


        </div>
      </div>


    </div>

    {%empty%}
    <h3>NO post found...</h3>

    {%endfor %}



  </div>



</section>

<div class="row">
  {% if posts.has_other_pages %}

  <ul class="pagination">

    {% if posts.has_previous %}
    <li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}"
        class="page-link">&laquo</a></li>

    <li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
    {% endif %}

    {%for i in posts.paginator.page_range %}
    {% if posts.number == i %}
    <li class="page-item"><a class="active page-link">{{i}}</a></li>
    {% else %}
    <li class="page-item"><a data-item="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
    {% endif %}
    {% endfor %}

    {% if posts.has_next %}
    <li class="page-item"><a data-item="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}"
        class="page-link">Last</a></li>

    <li class="page-item"><a data-item="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}"
        class="page-link">&raquo</a></li>
    {% endif %}
  </ul>
  {% endif %}
</div>

<script type="text/javascript">
  let searchForm = document.getElementById('searchForm')
  let pageLinks = document.getElementsByClassName('page-link')

  for (var i = 0; pageLinks.length; i++) {
    pageLinks[i].addEventListener('click', () => setTimeout(function (e) {
      e.preventDefault()
      let page = this.dataset.page
      console.log('Page:', page)
      searchForm.innerHTML += '<input value="$(page)" name="page" hidden >'
      searchForm.submit()
    }))
  }
</script>

{% endblock content %}

my_portfolio/base/templates/base/profile.html
{%extends 'base/main.html'%}

{% block content %}

<h1>profile page</h1>

{% endblock content %}